### ISSUE TITLE
Support documenting Skylark Aspects

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/stardoc#1]
Tracking bug for implementing support for documenting [Aspects](https://bazel.build/versions/master/docs/skylark/aspects.html).

**Comment by UebelAndre** [comment]
This would be a nice thing to have

**Comment by tetromino** [comment]
We almost certainly would be able to add this as part of https://github.com/bazelbuild/stardoc/issues/69.

**Comment by tetromino** [comment]
I believe this was fixed years ago (probably by 2c81ab8f05a0d89fcb926b8aa7d8345c3b643faf)
