### ISSUE TITLE
Have a new release for stardoc

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/stardoc#109]
The last release for stardoc is still in 2019, and Bazel itself uses a commit that's newer than that release.
Ideally we don't want downstream users to pin point a certain un-verified commit.

This is also blocking https://github.com/bazelbuild/bazel-central-registry/issues/7

Please have a new stardoc release.

**Comment by tetromino** [comment]
Will release a new version as soon as we add a proper way to generate a release tarball: https://github.com/bazelbuild/stardoc/pull/111

**Comment by tetromino** [comment]
Released https://github.com/bazelbuild/stardoc/releases/tag/0.5.0
