### ISSUE TITLE
On Windows, Stardoc inserts carriage return characters after processing each template

### ISSUE THREAD

**Issue by tetromino** [bazelbuild/stardoc#110]
On Windows, Stardoc seems to insert a superfluous carriage return character in markdown output at the end of each processed template (*not* end of each line).

This means Stardoc's output on Windows is not byte-identical to the output Linux - which, among other things, prevents us from migrating to bazel-skylib's diff_test.

See the CI runs for https://github.com/bazelbuild/stardoc/commit/900f9f085699e79a17ba22ed0493b4163c1db82f which passed on Linux and macOS (https://buildkite.com/bazel/stardoc/builds/235#44e0a148-360c-48e3-aa07-215f796d5b7c) but failed on Windows (https://buildkite.com/bazel/stardoc/builds/235#6dc4c463-853d-47b3-8fee-9dffcdf30e2d).

**Comment by alexeagle** [comment]
FWIW I think there may be a bug in bazel-skylib. I've had to bypass Windows CI for some rules_nodejs uses of `diff_test`, again the content should be identical on linux. 
https://github.com/bazelbuild/rules_nodejs/blob/fafb12fe6c9bb39b064665b652b645468aa9bf6b/docs/BUILD.bazel#L63 is the spot.

**Comment by alexeagle** [comment]
Ah, got out a windows laptop and you're right. My other diff_test problems were also because of stardoc output being platform-sensitive.
