### ISSUE TITLE
stardoc should gracefully handle borked dependencies

### ISSUE THREAD

**Issue by jonathan-enf** [bazelbuild/stardoc#128]
Currently, stardoc recurses through all loaded .bzl files to produce correct documentation.  This requires a correct bzl_library (with correct dependencies and visibility) not only for the .bzl file being documented, but for the complete transitive dependency set.

This makes stardoc fragile.  In my use case, one package added a dependency on rule_pkg.bzl, which had visibility set incorrectly (already fixed in https://github.com/bazelbuild/rules_pkg/commit/76f5651ed90209ffb9eff40fef3cee19a1f1e8a3 but not yet released), which broke our automated stardoc-based generation flow.

In the wild and wooly world of the internets, this is just going to happen from time to time.  It would be great if stardoc could more gracefully handle broken dependencies: just raise a warning that some loaded block couldn't be found, but then valiantly soldier on using the information that is available.  For the vast majority of cases, a missing dependency won't matter.

Thanks!

**Comment by jonathan-enf** [comment]
Just pinging this issue.  I felt certain this issue would be a dupe of an existing issue, but couldn't find such an issue when I searched the issues list.  Is this a reasonable request?

**Comment by tetromino** [comment]
This is a reasonable request. It cannot be accomplished with the current architecture, but we will try to fix it as part of the rewrite in #69.

**Comment by jonathan-enf** [comment]
In case this is useful for anyone else, I created a very limited documentation generator that solves this issue for me and released it under GPL license.   https://github.com/enfabrica/enkit/tree/master/tools/bzldoc

It works by parsing bzl files itself with the python AST -- but doesn't do anything fancy like import rules from other packages or transform data.  I suspect that eventually bazel will implement a feature enabling it to dump fully processed rule metadata itself -- when that happens, I'll adapt bzldoc to use that metadata instead of parsing bzl itself.

**Comment by tetromino** [comment]
Half of this (the renderer side) was fixed by https://github.com/bazelbuild/stardoc/commit/dbe010734e94081487fb6c47e27085b59daf77aa

The second half will be fixed by an soon-upcoming PR.
