### ISSUE TITLE
Warning when upgrading to 0.6.0 using bzlmod

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/stardoc#174]
```
DEBUG: /Users/brentley/Developer/rules_xcodeproj/bazel-output-base/external/rules_jvm_external~4.5/coursier.bzl:506:22: The inputs to rules_jvm_external~4.5~maven~stardoc_maven_install.json have changed, but the lock file has not been regenerated. Consider running 'bazel run @unpinned_rules_jvm_external~4.5~maven~stardoc_maven//:pin'
```

I find it odd that I should have to run any commands when using bzlmod?

**Comment by fmeum** [comment]
I believe that this warning is triggered because of https://github.com/bazelbuild/stardoc/blob/799f388ecdb790e6d7f6bf6eebaa2c0befb807fe/MODULE.bazel#L16-L17.

Ideally rules_jvm_external wouldn't show this warning if the `maven` usage is from a non-root module - the user can't update the pin anyway.
