### ISSUE TITLE
0.6.0 dropped support for Bazel 5

### ISSUE THREAD

**Issue by brentleyjones** [bazelbuild/stardoc#175]
```
ERROR: Traceback (most recent call last):
        File "/Users/administrator/buildbuddy.noindex/remote_build/ca55a571-9055-414a-9e79-47dbf42b7194/repo-root/bazel-output-base/external/io_bazel_stardoc/stardoc/private/stardoc.bzl", line 189, column 7, in <toplevel>
                } | _common_renderer_attrs,
Error: unsupported binary operation: dict | dict
ERROR: error loading package 'docs': at /Users/administrator/buildbuddy.noindex/remote_build/ca55a571-9055-414a-9e79-47dbf42b7194/repo-root/bazel-output-base/external/io_bazel_stardoc/stardoc/stardoc.bzl:19:6: initialization of module 'stardoc/private/stardoc.bzl' failed
```

Not sure if intentional. Seems it could not use the new Starlark dictionary operation to maintain broader support.

**Comment by tetromino** [comment]
We do not test Stardoc with older Bazel releases. So I was surprised that this usage of the `|` operator is the *only* thing preventing Stardoc 0.6 from working with Bazel 5.

Normally, we would not go out of our way to restore compatibility with older Bazel releases, but in this case, given how completely trivial the change is, we probably ought to do it.

Note that a Stardoc release in the near future - tentatively, 0.7, probably coming in early in 2024 - will drop compatibility with Bazel 5 and 6, and will require Bazel 7.
