### ISSUE TITLE
Stardoc is not usable by consumers in `0.6.2`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/stardoc#186]
I opened https://github.com/bazelbuild/rules_rust/pull/2129 and am getting issues the following build failure:
```
Error in fail: Failed to parse /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/dc2dbc2929304b001ce0cb65e3254023/external/io_bazel_stardoc/maven_install.json. It is not a valid maven_install.json file. Has this file been modified manually?
```
Additionally, it feels like there's an insane number of new macros required to use the tool. Can that be reduced somehow?

**Comment by UebelAndre** [comment]
Maybe someone on the Bazel team who’s familiar with bzlmod can help add support for it in rules_rust 😄

**Comment by tetromino** [comment]
Re rules_rust - it's diamond inheritance, as suspected.

Stardoc requires @rules_jvm_external >= 5.2
    
@rules_rust's prost and proto_protobuf transitively (via an obsolete @com_google_protobuf dependency) pull in @rules_jvm_external 4.1
    
My suggested workaround - see https://github.com/bazelbuild/rules_rust/commit/8755984f569899f3ff3f9ecf1d45906697b66b8b - is to move the Stardoc block above @rules_rust's prost and proto_protobuf block.
 
The real solution is bzlmod...

**Comment by tetromino** [comment]
I've updated the https://github.com/bazelbuild/stardoc/releases/tag/0.6.2 release page to discuss the WORKSPACE order dependence problem, and will add the text to the template in the maintainer's guide.

**Comment by tetromino** [comment]
> Maybe someone on the Bazel team who’s familiar with bzlmod can help add support for it in rules_rust 😄

@Wyverald would be a good person to talk to

**Comment by Wyverald** [comment]
@UebelAndre please take a look at the Bzlmod migration guide at https://bazel.build/external/migration. @meteorcloudy and I are happy to answer any questions and help with problems you encounter, but we don't have enough cycles to move the entire ecosystem to Bzlmod ourselves.

**Comment by UebelAndre** [comment]
@Wyverald thanks, there's open PRs to add bzlmod support but it doesn't appear any existing maintainers have bandwidth to come up to speed on bzlmod to be an effective reviewer. Support would be greatly appreciated.
