### ISSUE TITLE
Push 6.x to the BCR

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/stardoc#188]
The WORKSPACE setup has gotten too large to conveniently use,
but switching to bzlmod for doc generation is hampered by an old release.

**Comment by fmeum** [comment]
It's available already: https://github.com/bazelbuild/bazel-central-registry/tree/main/modules/stardoc/0.6.2

**Comment by aiuto** [comment]
I'm scratching my head.   I just git pulled the repo and i am not seeing it.
OK. I believe you. I'll figure out what typo I made.
