### ISSUE TITLE
Migrate to Bzlmod for managing external dependencies

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/stardoc#189]
With future Bazel LTS versions, Bzlmod will become the default system for external dependencies management.

Please consider migrating all your external dependencies in WORKSPACE to MODULE.bazel

For more information, please check https://github.com/bazelbuild/bazel/issues/18958

**Comment by tetromino** [comment]
I think as part of Stardoc 0.7 (or whatever the next significant versioned release will be), we ought to switch to bzlmod, finally drop the bundled jar with the legacy extractor, and require Bazel 7
