### ISSUE TITLE
[Bazel CI] proto_format_test_e2e_test is failing at Bazel@HEAD


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/stardoc#228]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3890#018fc7ad-a52d-4525-9c42-43bdfd4f1c5a

 Platform: Ubuntu

 Logs: 
```

FAIL: [//test:proto_format_test_e2e_test 
``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/stardoc
git reset 666b7ba7124b9af9c531c6c5f2013f69b27ea144  --hard
export USE_BAZEL_VERSION=00a0837f86d6086bba4bbcfdb6ab354edb7f3b63 
 ``` 
 CC Greenteam @comius

**Comment by tetromino** [comment]
This is expected after https://github.com/bazelbuild/bazel/commit/bd1c3af2ea14e81268e940d2b8ba5ad00c3f08d7

I think we simply need to disable this test with Bazel@HEAD since the golden output depends on the Bazel version.

**Comment by sgowroji** [comment]
@tetromino [https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3898#018fdc44-14ed-464e-b33d-630a5c82183b](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3898#018fdc44-14ed-464e-b33d-630a5c82183b) CI is still failing. Can you please take a look. Thanks!
