### ISSUE TITLE
Stardoc code should not be intertwined in Bazel source tree

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/stardoc#24]
This might be blocked on pulling Starlark out of Bazel. It seems very wrong that the formatting code is in the Bazel source. See https://github.com/bazelbuild/bazel/pull/9240 for reference

**Comment by brandjon** [comment]
The solution to this will be to create a public API for exporting documentation from `bazel query`. Then version skew won't be such a big issue. At that point, the Java code can be modified to read bazel query output, and moved to this repo.

**Comment by achew22** [comment]
Is the idea to use a [`genquery`](https://docs.bazel.build/versions/master/be/general.html#genquery) or something like it, setting it up to output in `proto` mode and then writing a rule that takes that proto in as an argument and generates documentation?

**Comment by brandjon** [comment]
Yes, "something like it". The main work will be defining a representation for objects created during Bazel's loading phase -- not just targets as it is today, but also information about the .bzl load graph and the top-level symbols defined in .bzl modules. But yes, once you have that, you could imagine reifying it back as a build target the way `genquery` does for target graph information. Then Stardoc can retrieve it without having to invoke a separate Bazel process.

**Comment by aiuto** [comment]
I think a fun design point will be the interaction between what you can do
with just parsing, vs. what you might get if you did a full evaluation in
the context of a workspace. One could imagine a .bzl file that creates a
rule with different definitions depending on the value of a constant from
some other repository.

   - Is this allowed?  Let's presume so.
   - Is that what people want? Open question. I might want a single
   document, but with some attributes tagged as "only available if rules_foo >
   1.2".

And, of course, will every bazel build pay a memory penalty for having doc
strings in memory?

**Comment by brandjon** [comment]
> will every bazel build pay a memory penalty for having doc strings in memory?

The docstrings are already there, either persisted by the interpreter (in the case of function docstrings) or the implementation of the built-in type (for things that take a `doc=` param). But there should be negligible memory impact, since these structures are few in number compared to the number of configured targets.

>  what you can do with just parsing

Note that Stardoc currently does more than just parsing. It does real Starlark evaluation, but with fake Build Language definitions. I'm not sure exactly how it handles bzls from multiple repositories.

> One could imagine a .bzl file that creates a rule with different definitions depending on the value of a constant from some other repository.

Perhaps, but under the new design, you get the semantics of whatever your real build does, relative to the documentation target.

**Comment by aiuto** [comment]
bzl from multiple repositories can be interesting.  Let's say I create rules_fortran and I share the c++ linker, so I use a provider like @rules_cc//def.bzl%CcCommon.   I might want to document that a method returns CcCommon. It would be nice if the emitted markup language had easily parsable links so that I could turn it into an HREF (or markdown link) to either the docs at github.com/bazelbuild/rules_cc OR my own repository.   I don't think StarDoc has to do that itself - dealing with the infinite variety of ways people want to publish internal docs is a never ending battle. It just needs to preserve the external repo name and path to the method/provider/rule in the output so anyone can post process that to meet their needs.

**Comment by brandjon** [comment]
Right, from Stardoc's POV, a symbol is uniquely identified by its defining bzl label and its name in the module's global namespace. The rendering tooling can worry about how to convert that into canonical urls.

**Comment by brandjon** [comment]
Marking as dup of #69, we can continue discussion there.
