### ISSUE TITLE
[Bazel CI] Test failures when building against gRPC runtime


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/stardoc#242]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3965#0190810d-9f64-4673-b5e5-c459fba979f3

 Platform: Ubuntu

 Logs: 
```
FAIL: [0m//test:proto_format_test (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a334b053a4cd897f376f2e49b844ad93/execroot/_main/bazel-out/k8-fastbuild/testlogs/test/proto_format_test/test_attempts/attempt_1.log)
FAIL: [0m//test:proto_format_test (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a334b053a4cd897f376f2e49b844ad93/execroot/_main/bazel-out/k8-fastbuild/testlogs/test/proto_format_test/test_attempts/attempt_2.log)
FAIL: [0m//test:proto_format_test (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a334b053a4cd897f376f2e49b844ad93/execroot/_main/bazel-out/k8-fastbuild/testlogs/test/proto_format_test/test.log)
FAILED: [0m//test:proto_format_test (Summary)
FAIL: [0m//test:macro_kwargs_legacy_test (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a334b053a4cd897f376f2e49b844ad93/execroot/_main/bazel-out/k8-fastbuild/testlogs/test/macro_kwargs_legacy_test/test_attempts/attempt_1.log)
FAIL: [0m//test:macro_kwargs_legacy_test (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a334b053a4cd897f376f2e49b844ad93/execroot/_main/bazel-out/k8-fastbuild/testlogs/test/macro_kwargs_legacy_test/test_attempts/attempt_2.log)
FAIL: [0m//test:macro_kwargs_legacy_test (Exit 1) (see /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a334b053a4cd897f376f2e49b844ad93/execroot/_main/bazel-out/k8-fastbuild/testlogs/test/macro_kwargs_legacy_test/test.log)
FAILED: [0m//test:macro_kwargs_legacy_test (Summary)

``` 
 Culprit: 

 Steps:
  ``` 
 git clone https://github.com/bazelbuild/stardoc
git reset da374a508b5a5f82e1e00f94889f04f9f86ca1fe  --hard
export USE_BAZEL_VERSION=674e67bdc3c08b5ac72d5f1ce456bb52766a0f84
bazel test  //test:proto_format_test //test:macro_kwargs_legacy_test 
 ``` 
 CC Greenteam @meteorcloudy

**Comment by sgowroji** [comment]
CC @tetromino

**Comment by tetromino** [comment]
//test:proto_format_test and //test:macro_kwargs_legacy_test are tagged `manual` because they are Bazel 7 only, and are expected to produce a different output when using Bazel 8.

See https://github.com/bazelbuild/stardoc/blob/da374a508b5a5f82e1e00f94889f04f9f86ca1fe/test/BUILD#L50 and https://github.com/bazelbuild/stardoc/blob/da374a508b5a5f82e1e00f94889f04f9f86ca1fe/test/BUILD#L242

Why are we running tests which are tagged `manual` in the bazel-at-head-plus-downstream pipeline?

**Comment by tetromino** [comment]
Oh, it's even worse - bazel-at-head-plus-downstream is running the task explicitly described as "Stardoc golden tests requiring Bazel 7.2" task (defined at https://github.com/bazelbuild/stardoc/blob/da374a508b5a5f82e1e00f94889f04f9f86ca1fe/.bazelci/presubmit.yml#L116) using Stardoc 8 prerelease :)

Naturally, it fails.

**Comment by tetromino** [comment]
I've filed an issue at https://github.com/bazelbuild/continuous-integration/issues/1999

I don't see this as a Stardoc bug, IMHO

**Comment by tetromino** [comment]
Never mind, it is a Stardoc bug/misconfiguration; see https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md#downstream-project-policies for posterity
