### ISSUE TITLE
`mirror.bazel.build` missing stardoc `0.7.0`

### ISSUE THREAD

**Issue by albertocavalcante** [bazelbuild/stardoc#246]
For `WORKSPACE` projects, the release https://github.com/bazelbuild/stardoc/releases/tag/0.7.0 use this `http_archive` directive:

```starlark
http_archive(
    name = "io_bazel_stardoc",
    sha256 = "dd7f32f4fe2537ce2452c51f816a5962d48888a5b07de2c195f3b3da86c545d3",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/stardoc/releases/download/0.7.0/stardoc-0.7.0.tar.gz",
        "https://github.com/bazelbuild/stardoc/releases/download/0.7.0/stardoc-0.7.0.tar.gz",
    ],
)
```

However https://mirror.bazel.build/github.com/bazelbuild/stardoc/releases/download/0.7.0/stardoc-0.7.0.tar.gz returns `404`.

**Comment by tetromino** [comment]
Re-mirrored the file, thank you very much for reporting! (I think we must have failed to set the expiration age it.)
