### ISSUE TITLE
Rule documentation documents for visible name, not exported name

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/stardoc#33]
If one does:

```
my_rule = rule(...)
foo_rule = my_rule

```
and then generates documentation for `foo_rule`, it may be confusing to users that invoking `bazel query` on targets of `foo_rule` actually show the rule of these targets as being `my_rule`.
We may want to consider automatically documenting the 'query-visible' name of a rule.

**Comment by brandjon** [comment]
This is likely fixed by a [pending change](https://bazel-review.googlesource.com/c/bazel/+/150431).
