### ISSUE TITLE
writing_stardoc.md doesn't seem to say how to use markup within the doc string

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/stardoc#36]
Historically (skydoc) some areas had to be markdown, some had to be html.  What is the final decision in stardoc?

Hopefully it can be all just basic markdown, and then the templates would know to always apply the same types of transforms for all cases to generate their final format.

**Comment by laurentlb** [comment]
@c-parsons Did we have a decision on this?

**Comment by c-parsons** [comment]
Markdown instead of html:

https://github.com/bazelbuild/stardoc/blob/master/docs/advanced_stardoc_usage.md#docstring-formatting

**Comment by c-parsons** [comment]
(please feel free to elaborate in the documentation where you'd expect to see this information, if you think the above link is insufficient!)
