### ISSUE TITLE
cross-repository references broken in Bazel 2.0

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/stardoc#43]
Noted here:

https://github.com/bazelbuild/bazel/issues/10131#issuecomment-566558593

the pattern of handling cross-repository references which was introduced for rules_rust (and I then borrowed in rules_nodejs) is broken by the next upcoming Bazel release

**Comment by alexeagle** [comment]
Ping - now that Bazel 2.0 is shipped, our CI went red on bazelci

**Comment by c-parsons** [comment]
I believe this was caused by the Bazel flag flip `--incompatible_remap_main_repo` in 2.0. #44 should fix this regardless of that flag value.
