### ISSUE TITLE
Better support for rules with wrapper macros

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/stardoc#54]
Many rules have a little wrapper around them to calculate default values. The best experience for the user is to see a single unified attribute list for the user visible part (the macro). But we also want to document the attributes on the rule itself. If we could link the macro and implementation in some way, we could 
- highlight the fact in the docs.  foo_library (implemented by foo_library_impl)
- show a unified attribute list without having to copy up to the macro (duplicates work) or (falsely) claim the default setting on the rule documentation.

Another potential win from semantically linking the wrapper and implementation is that we can have buildifier stop complaining about \*\*kwargs style args, when we want to pass most from the wrapper to the rule untouched.

**Comment by adam-azarchs** [comment]
Seems like a duplicate of #27

**Comment by aiuto** [comment]
Yes. It does. I went through the open bugs, but the title of the other didn't jump out at me.
