### ISSUE TITLE
Stardoc doesn't work with Bazel head

### ISSUE THREAD

**Issue by achew22** [bazelbuild/stardoc#64]
Test setup:

```
cd
git clone https://github.com/bazelbuild/stardoc
git clone https://github.com/bazelbuild/bazel
cat <<EOF > stardoc/.bazelrc
common --override_repository=io_bazel=${HOME}/bazel
EOF
```

Configure the bisect to run between `HEAD` and `b2b9fa00d7d168e9553cfc9fe381928e8e246176` (which is currently in the workspace and I checked worked).

```
git bisect start
git bisect bad HEAD
git bisect good b2b9fa00d7d168e9553cfc9fe381928e8e246176
```

Now run the bisect:

```
git bisect run bash -c '(set -e && cd ~/stardoc && ./update-release-binary.sh)'
```

This appears to be the [bad commit](https://github.com/bazelbuild/bazel/commit/54491ef4e4be8d09f4473141212c148fa0bffb2b).

```
54491ef4e4be8d09f4473141212c148fa0bffb2b is the first bad commit
commit 54491ef4e4be8d09f4473141212c148fa0bffb2b
Author: ahumesky <ahumesky@google.com>
Date:   Thu Jul 30 16:57:33 2020 -0700

    Add AndroidSdkInfo to Bazel behind --experimental_google_legacy_api

    RELNOTES: None.
    PiperOrigin-RevId: 324113180

 .../devtools/build/docgen/SymbolFamilies.java      |   4 +-
 .../lib/bazel/rules/BazelRuleClassProvider.java    |   4 +-
 .../starlarkbuildapi/android/AndroidBootstrap.java |   9 +-
 .../google/devtools/build/skydoc/SkydocMain.java   |   6 +-
 .../build/skydoc/fakebuildapi/android/BUILD        |   3 +
 .../android/FakeAndroidSdkProvider.java            | 159 +++++++++++++++++++++
 6 files changed, 179 insertions(+), 6 deletions(-)
 create mode 100644 src/main/java/com/google/devtools/build/skydoc/fakebuildapi/android/FakeAndroidSdkProvider.java
bisect run success
```

and the build error is:

```
ERROR: <snip>/external/io_bazel/src/main/java/com/google/devtools/build/lib/exec/BUILD:243:13: no such package '@remoteapis//': The repository '@remoteapis' could not be resolved and referenced by '@io_bazel//src/main/java/com/google/devtools/build/lib/exec:spawn_log_context'
ERROR: Analysis of target '@io_bazel//src/main/java/com/google/devtools/build/skydoc:skydoc_deploy.jar' failed; build aborted: Analysis failed
```

Unfortunately, from looking at the diff I can't tell why this CL would be an issue. Do you have any ideas? Why `@remoteapis`?

**Comment by larsrc-google** [comment]
It works if I don't add the override in stardoc/.bazelrc. I haven't seen that override done before, what is it for?

**Comment by achew22** [comment]
@larsrc-google, thanks for taking a look into this so quickly.

[`--override_repository`](https://docs.bazel.build/versions/master/command-line-reference.html#flag--override_repository) is a flag that lets you replace a remote repository with a local one for testing purposes. For example, if you're working on new feature for `rules_foo` and that is consumed in your repo, you could use `--override_repository` to temporarily replace the `@rules_foo` namespace with a local directory. It is probably better [described](https://docs.bazel.build/versions/master/external.html#overriding-repositories-from-the-command-line) in the docs than anything I could say in here.

The invocation that I have in there replaces `io_bazel` with the copy that's checked out in your home directory so that when the bisect is running git can move the bisect without forcing the user to manually modify the workspace.

If you would like to test this without the pain of running a git bisect you could change the `git_repository` in `WORKSPACE` to these values and confirm that it does/does not build:

https://github.com/bazelbuild/stardoc/blob/87dc99cfe1baa9255c607ac0229bfd33a65367f5/WORKSPACE#L14-L19

| Commit | Description | Status |
|-----|-----|----|
| `b2b9fa00d7d168e9553cfc9fe381928e8e246176` | The commit currently referenced by WORKSPACE | PASS |
| `052e9b704266c28f801c7cdb25de88c0414fbea0` | The commit immediately preceding the suspected bad commit | PASS |
| `54491ef4e4be8d09f4473141212c148fa0bffb2b` | The first broken commit my bisect found | FAIL |
| `d53de71008b28ecda9b50d0b96446b0b0fdc618d` | HEAD as of August 25 at 9:47am Pacific | FAIL |

**Comment by achew22** [comment]
Friendly ping 😄

**Comment by larsrc-google** [comment]
Thanks for the explanation. I'm new on the Bazel team, and there's still so much to learn.

**Comment by alandonovan** [comment]
On Thu, 27 Aug 2020 at 04:54, larsrc-google <notifications@github.com>
wrote:

> I'm new on the Bazel team, and there's still so much to learn.
>
That never goes away, I'm afraid.

>

**Comment by segiddins** [comment]
Try https://github.com/bazelbuild/stardoc/pull/65 and see if it fixes the issue for you?

**Comment by segiddins** [comment]
@achew22 this has now been fixed upstream in bazel, try with latest HEAD

**Comment by achew22** [comment]
I don't think I'm going to get cycles to get back to this for a couple of days and feel bad leaving this open if there isn't an issue. I'll reopen if it turns out it isn't actually fixed. Thanks @c-parsons, @segiddins, & @larsrc-google, you rock!
