### ISSUE TITLE
Documentation from hidden rule attributes in public macro

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/stardoc#67]
Say there's a `.bzl` file similar to the following
```python
_my_rule = rule(
    implementation = _my_rule_impl,
    doc = "my special rule",
    attrs = {
        "a": attr.string(
            doc = "Documentation for 'a'",
        ),
        "b": attr.string(
            doc = "Documentation for 'b'",
        ),
    }
)

def my_rule(name, **kwargs):
    """My special rule wrapper
    
    Args:
        name: name of the rule
        **kwargs: _my_rule attributes

    Returns:
        The name of the rule
    """

    _my_rule(
        name = "my_" + name,
        **kwargs,
    )

    return "my_" + name
```

Is it possible to generate docs for `_my_rule`'s attributes without making it public?

**Comment by UebelAndre** [comment]
@c-parsons @laurentlb @jin I'm happy to take some work-around, but would definitely like to get your input 😅

**Comment by c-parsons** [comment]
I believe this is somewhat a duplicate of https://github.com/bazelbuild/stardoc/issues/27 and https://github.com/bazelbuild/stardoc/issues/62 in the general case.

That said, you can document private symbols by specifying it as an entry in [symbol_names](https://github.com/bazelbuild/stardoc/blob/master/docs/stardoc_rule.md#stardoc-symbol_names). (By default, private symbols are omitted, but you can override this by specifying them explicitly!)

**Comment by UebelAndre** [comment]
Oh man! #27 is exactly what I want! Any idea what the status of that is?

**Comment by UebelAndre** [comment]
Actually, I'll close this and ask that there.
