### ISSUE TITLE
Document ability to call Java methods from within vm templates

### ISSUE THREAD

**Issue by mobileink** [bazelbuild/stardoc#88]
Hey!  I just inadvertently discovered that I can access the Java api in my custom template. How nice!  So I can put the following in my rules.vm file:

```
#if(!${attribute.getProviderNameGroupList().isEmpty()})
Providers: #foreach ($pg in ${attribute.getProviderNameGroupList()})
#foreach ($pl in ${pg.getProviderNameList()}) [${pl}](providers_ocaml.md#${pl.toLowerCase()})
#end
#end
#end
```

Note the `pl.toLowerCase()`, that calls the Java String API.  I guess I might have known this if I knew something about Velocity but I don't.  I recommend you note this is in the documentation.

**Comment by brandjon** [comment]
What I'm wondering is whether there's any Java API that can be called here that we don't want exposed to users. But I imagine we're protected from that by the fact that the renderer binary reads protos, and doesn't interact with Bazel code directly.

**Comment by alandonovan** [comment]
@brandjon Good question. I think you're right, but it should certainly be documented in the .proto file that this forms a stable published interface between the Java code and various (in effect) scripts and style sheets defined by users that we cannot see.

**Comment by brandjon** [comment]
Deduping to #39.
