### ISSUE TITLE
Show example load() call for each rule

### ISSUE THREAD

**Issue by cvrebert** [bazelbuild/stardoc#95]
Whenever I start using a new Starlark rule, the first step is to `load()` it in my BUILD file. Therefore it would be handy if the Stardoc output for each rule showed an appropriate `load()` statement that I could directly copy-paste. That way, users don't have to manually tweak the path to the `.bzl` file, change the final slash to a colon, etc., which is pure avoidable tedium.

**Comment by brandjon** [comment]
That sounds like a nice feature. It might not be applicable in all environments since the repo might be imported by a different non-standard name in the user's WORKSPACE file, but that use is comparatively rare.

**Comment by alexeagle** [comment]
FWIW I've started adding this feature in https://docs.aspect.dev

**Comment by tetromino** [comment]
Now that we have `OriginKey` in the protos, this should be fairly easy to implement in the renderer for anyone who is interested
