### ISSUE TITLE
use of `json` module causes failures

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/stardoc#96]
If I try to generate documentation for a file using the [json](https://docs.bazel.build/versions/master/skylark/lib/json.html) module, I'm faced with the following error:
```
./external/rules_rust/crate_universe/defs.bzl:35:20: name 'json' is not defined
./external/rules_rust/crate_universe/defs.bzl:46:32: name 'json' is not defined
./external/rules_rust/crate_universe/defs.bzl:48:12: name 'json' is not defined
./external/rules_rust/crate_universe/defs.bzl:329:12: name 'json' is not defined
./external/rules_rust/crate_universe/defs.bzl:357:12: name 'json' is not defined
com.google.devtools.build.skydoc.SkydocMain$StarlarkEvaluationException: name 'json' is not defined (+ 4 more)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:456)
	at com.google.devtools.build.skydoc.SkydocMain.recursiveEval(SkydocMain.java:465)
	at com.google.devtools.build.skydoc.SkydocMain.eval(SkydocMain.java:325)
	at com.google.devtools.build.skydoc.SkydocMain.main(SkydocMain.java:228)
Stardoc documentation generation failed: name 'json' is not defined (+ 4 more)
```

Stardoc should support this.

**Comment by UebelAndre** [comment]
@brandjon I'm wondering if there's a simple re-export you can do to quickly address this?

**Comment by UebelAndre** [comment]
@tetromino might you also be able to address this? Again, hoping it's a relatively quick effort.

**Comment by tetromino** [comment]
Weird - this should have been fixed a while ago by https://github.com/bazelbuild/bazel/commit/ac390caf474826e6bbecab2129f20c3354f3f7a3

**Comment by UebelAndre** [comment]
Doesn't `stardoc` need to be re-exported? I think a similar commit to https://github.com/bazelbuild/stardoc/commit/a8c608986b4f27416ce085495617a6c9b3b40195 would be required.

**Comment by tetromino** [comment]
It was already re-exported in https://github.com/bazelbuild/stardoc/commit/1467f5687e75472fdb045f3ceac7f52c8a11d9c5 which updated the jars to Bazel head as of 2020-12-30. And I see that you are using the latest stardoc commit in https://github.com/bazelbuild/rules_rust/commit/8ee8947022b349c87a0424f038be0f0e45bfa5db...

**Comment by tetromino** [comment]
Ah, I see the problem - https://github.com/bazelbuild/stardoc/commit/1467f5687e75472fdb045f3ceac7f52c8a11d9c5 didn't actually update the binaries.
